### ISSUE TITLE
cellxgene-gateway fails to start any server

### ISSUE THREAD

**Issue by klkeys** [Novartis/cellxgene-gateway#53]
running a clean install of `cellxgene-gateway==0.3.7`, ships with `cellxgene==0.19.0`

when I click a dataset in the File Crawler, the server refuses to launch `cellxgene`:
```
Traceback (most recent call last):
File "/usr/local/bin/cellxgene", line 8, in <module> sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) 
    File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx)
      File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1256, in invoke Command.invoke(self, ctx)
        File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params)
          File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) 
            File "/usr/local/lib/python3.8/dist-packages/server/cli/cli.py", line 30, in cli log_upgrade_check()
              File "/usr/local/lib/python3.8/dist-packages/server/cli/upgrade.py", line 25, in log_upgrade_check if version_gt(latest_release, __version__):
                File "/usr/local/lib/python3.8/dist-packages/server/cli/upgrade.py", line 80, in version_gt for left, right in zip(split_version(left_version), split_version(right_version)):
                  File "/usr/local/lib/python3.8/dist-packages/server/cli/upgrade.py", line 76, in split_version return [int(match.group(group)) for group in ["major", "minor", "patch"]]
                    File "/usr/local/lib/python3.8/dist-packages/server/cli/upgrade.py", line 76, in <listcomp> return [int(match.group(group)) for group in ["major", "minor", "patch"]]

AttributeError: 'NoneType' object has no attribute 'group'
```
as far as I can tell, `cellxgene-gateway` keeps looking for a sever update or upgrade and has not formatted the query correctly...?

**Comment by klkeys** [comment]
to clarify: the previous error trace was what I got from the browser. my actual server log shows this:
``` 
2021-09-28 23:32:22,827:cellxgene_gateway:INFO:Got required env: {'CELLXGENE_LOCATION': '/usr/local/bin/cellxgene'}
 2021-09-28 23:32:22,827:cellxgene_gateway:INFO:Got optional env: {EXTERNAL_HOST 'my.url.com', 'EXTERNAL_PROTOCOL': None, 'GATEWAY_IP': None, 'GATEWAY_PORT': 80, 'GATEWAY_EXTRA_SCRIPTS': None, 'GATEWAY_TTL': None, 'GATEWAY_ENABLE_ANNOTATIONS': False, 'GATEWAY_ENABLE_BACKED_MODE': False, 'CELLXGENE_ARGS': None, 'CELLXGENE_DATA': '/home/cellxgene_data', 'PROXY_FIX_FOR': 0, 'PROXY_FIX_PROTO': 0, 'PROXY_FIX_HOST': 0,         'PROXY_FIX_PORT': 0, 'PROXY_FIX_PREFIX': 0}
 * Serving Flask app "cellxgene_gateway.gateway" (lazy loading)
 * Environment: production
    WARNING: This is a development server. Do not use it in a production deployment.
     Use a production WSGI server instead.
   * Debug mode: off 
 2021-09-28 23:32:22,833:werkzeug:INFO: * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 2021-09-28 23:32:24,954:cellxgene_gateway:INFO:launching yes | /usr/local/bin/cellxgene launch /home/cellxgene_data/pbmc3k.h5ad --port 8000 --host 127.0.0.1 --disable-annotations
 2021-09-28 23:32:25,961:werkzeug:INFO:10.20.130.3 - - [28/Sep/2021 23:32:25] "#033[37mGET /view/pbmc3k.h5ad/ HTTP/1.1#033[0m" 200 -
 Exception in thread Thread-4:
 Traceback (most recent call last):
 File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.8/threading.py", line 870, in run 
      self._target(*self._args, **self._kwargs)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/cellxgene_gateway/subprocess_backend.py", line 82, in launch
      raise ProcessException.from_cache_entry(cache_entry)
 cellxgene_gateway.process_exception.ProcessException
 ```

**Comment by klkeys** [comment]
perhaps this is a problem from within `cellxgene` itself? I can recap the error on the server from a shell like this:

**commands**
```
export CELLXGENE_LOCATION=`which cellxgene`
$CELLXGENE_LOCATION launch /home/cellxgene_data/pbmc3k_example.h5ad 
```

**error**
```
Traceback (most recent call last):
  File "/usr/local/bin/cellxgene", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/server/cli/cli.py", line 30, in cli
    log_upgrade_check()
  File "/usr/local/lib/python3.8/dist-packages/server/cli/upgrade.py", line 25, in log_upgrade_check
    if version_gt(latest_release, __version__):
  File "/usr/local/lib/python3.8/dist-packages/server/cli/upgrade.py", line 80, in version_gt
    for left, right in zip(split_version(left_version), split_version(right_version)):
  File "/usr/local/lib/python3.8/dist-packages/server/cli/upgrade.py", line 76, in split_version
    return [int(match.group(group)) for group in ["major", "minor", "patch"]]
  File "/usr/local/lib/python3.8/dist-packages/server/cli/upgrade.py", line 76, in <listcomp>
    return [int(match.group(group)) for group in ["major", "minor", "patch"]]
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by alokito** [comment]
Thanks for reaching out. It looks like 0.19.0 was released three hours ago. I would recommend downgrading to 0.18.0 for now. We are still running 0.16.8 in production, but we should probably upgrade to at least 0.18.0.

**Comment by klkeys** [comment]
a downgrade to 0.16.8 threw the same error
```
pip3 install cellxgene==0.16.8 ## done
$CELLXGENE_LOCATION launch /home/cellxgene_data/pbmc3k_example.h5ad ## same error
```
but this works:
```
ubuntu@ip-10-84-96-13:~$ $CELLXGENE_LOCATION --version ## [cellxgene] Version 0.16.8
ubuntu@ip-10-84-96-13:~$ $CELLXGENE_LOCATION --no-upgrade-check launch /home/cellxgene_data/pbmc3k_example.h5ad ## success!
```
so my guess is that `cellxgene` checks for an upgrade upon running.

is there a way to turn this off in `cellxgene-gateway`? that might solve my problem.

**Comment by klkeys** [comment]
per the [`README`](https://github.com/Novartis/cellxgene-gateway/blob/620181ae4d2ae10eddcf960e081a4f564a0a13ef/README.md#L71), I tried
```
export CELLXGENE_ARGS="--no-update-check"
```
which seems to have passed correctly, according to the log:
```
2021-09-29 00:48:28,723:cellxgene_gateway:INFO:launching yes | /home/ubuntu/.local/bin/cellxgene launch /home/cellxgene_data/pbmc3k_example.h5ad --port 8000 --host 127.0.0.1 --disable-annotations --no-update-check ## <-- correct flag!
```
but I still get the error pointing to [`subprocess_backend.py:82`](https://github.com/Novartis/cellxgene-gateway/blob/620181ae4d2ae10eddcf960e081a4f564a0a13ef/cellxgene_gateway/subprocess_backend.py#L82)

**Comment by rpeckner-trex** [comment]
I am encountering the same error when running on a Docker container with Python 3.6.9 and cellxgene 0.17.0. Here is the error log:
```
2021-09-29 00:26:45,897:cellxgene_gateway:INFO:Got required env: {'CELLXGENE_LOCATION': '/usr/local/bin/cellxgene'}                                                                   
2021-09-29 00:26:45,897:cellxgene_gateway:INFO:Got optional env: {'EXTERNAL_HOST': 'localhost:5005', 'EXTERNAL_PROTOCOL': None, 'GATEWAY_IP': '172.17.0.1', 'GATEWAY_PORT': 5005, 'GAT
EWAY_EXTRA_SCRIPTS': None, 'GATEWAY_TTL': None, 'GATEWAY_ENABLE_ANNOTATIONS': True, 'GATEWAY_ENABLE_BACKED_MODE': True, 'CELLXGENE_ARGS': None, 'CELLXGENE_DATA': '', 'PROXY_FIX_FOR':
 0, 'PROXY_FIX_PROTO': 0, 'PROXY_FIX_HOST': 0, 'PROXY_FIX_PORT': 0, 'PROXY_FIX_PREFIX': 0}                                                                                            
2021-09-29 00:26:45,899:waitress:INFO:Serving on http://0.0.0.0:5005                                                                                                                  
view path=XXXXX.h5ad/, source_name=None, dataset=s3://XXXXX.h5ad, ann
otation_file= None, key=XXXXX.h5ad, source=s3                                                                                        
2021-09-29 00:27:04,993:cellxgene_gateway:INFO:launching yes | /usr/local/bin/cellxgene launch s3://XXXXX.h5ad --port 
8000 --host 127.0.0.1 --disable-annotations --backed                                                                                                                                  
Exception in thread Thread-2:                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                    
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner                                                                                                               
    self.run()                                                                                                                                                                        
  File "/usr/lib/python3.6/threading.py", line 864, in run                                                                                                                            
    self._target(*self._args, **self._kwargs)                                                                                                                                         
  File "/usr/local/lib/python3.6/dist-packages/cellxgene_gateway/subprocess_backend.py", line 82, in launch                                                                           
    raise ProcessException.from_cache_entry(cache_entry)                                                                                                                              
cellxgene_gateway.process_exception.ProcessException

```

**Comment by Jon-bioinfo** [comment]
+1 encountering this error with whichever cellxgene version 0.17, 0.18, 0.19. `--no-update-check` having no effect

**Comment by blrnw3** [comment]
The issue with the cellxgene 0.19.0 tag is now resolved

**Comment by klkeys** [comment]
the `cellxgene` 0.19.0 tag update seems to be the ticket

*package versions* (from `pip3 list`)
```
cellxgene              0.19.0
cellxgene-gateway      0.3.7
```
removed `export CELLXGENE_ARGS=" --no-update-check"` (oddly enough, doesn't work otherwise?)
and now `cellxgene-gateway` loads packages correctly! 🎉 

I'll close this for now, hopefully others also enjoy the fix on their end.
